apiVersion: v1
kind: Service
metadata:
  name: totem-express-user-service-svc
spec:
  selector:
    app: totem-express-user-service
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: LoadBalancer